Limit interactions
vodkhard/twittax pull request #8
Opened 2019-06-27 15:48 UTC by LouisHrg

Limit interactions, 1 per account for :
- Laaks
- Retwaats

2019-06-29 17:48 UTC, vodkhard requested changes

2019-06-29 17:48 UTC, vodkhard commented on js/components/twaat/item.js
> +      .is-retwaatax app-icon > svg {
useless, on passe direct la couleur en props

2019-06-29 17:48 UTC, vodkhard commented on js/components/twaat/item.js
> +        console.log(await twaatsRepository.hasUserRetwaat(this.item.id));
:warning:

2019-06-29 17:48 UTC, vodkhard commented on js/components/twaat/item.js
> +    this.userRetwaat = false;
```suggestion
    this.userRetwaated = false;
```

2019-06-29 17:48 UTC, vodkhard commented on js/components/twaat/item.js
> +      userRetwaat: Boolean,
```suggestion
      userRetwaated: Boolean,
```

2019-06-29 17:48 UTC, vodkhard commented on js/components/twaat/item.js
> +      })
```suggestion
      });
```

2019-06-29 17:48 UTC, vodkhard commented on js/components/twaat/item.js
> +      try {
j'en ai marre des try catch qui servent à rien, vire les

2019-06-29 17:48 UTC, vodkhard commented on js/data/repositroy/twaats.js
> +const hasUserRetwaat = id => firestore.collection(collection)
```suggestion
({ retwaats }) => retwaats.find(value => value.isEqual(firestore.collection('users').doc(fireauth.currentUser.uid))) || false;
```

2019-06-29 17:48 UTC, vodkhard commented on js/data/repositroy/twaats.js
> +const hasUserRetwaat = id => firestore.collection(collection)
Tu passes direct l'item en param ça évite de refaire une requête pour aller le chercher

2019-06-29 17:48 UTC, vodkhard commented on js/data/repositroy/twaats.js
> +const hasUserLaaked = id => firestore.collection(collection)
Same que `hasUserRetwaated`

2019-06-29 17:48 UTC, vodkhard commented on js/data/repositroy/twaats.js
> +const addLaaked = id => firestore.collection(collection)
```suggestion
const laak = id => firestore.collection(collection)
```

2019-06-29 17:48 UTC, vodkhard commented on js/data/repositroy/twaats.js
> +const addLaaked = id => firestore.collection(collection)
et on devrait faire dans cette même fonction l'ajout du twaat dans les laaked de l'user pour n'avoir qu'à call une fonction

2019-06-29 17:48 UTC, vodkhard commented on js/data/repositroy/twaats.js
> +const delLaaked = async id => firestore.collection(collection)
```suggestion
const unlaak = async id => firestore.collection(collection)
```

2019-06-29 17:48 UTC, vodkhard commented on js/data/repositroy/twaats.js
> +const delLaaked = async id => firestore.collection(collection)
Same que le add, les 2 ici

2019-06-29 17:48 UTC, vodkhard commented on js/data/repositroy/twaats.js
> +    laaks: fieldValue.arrayRemove(await firestore.collection('users').doc(fireauth.currentUser.uid)),
```suggestion
    laaks: fieldValue.arrayRemove(firestore.collection('users').doc(fireauth.currentUser.uid)),
```

2019-06-29 17:48 UTC, vodkhard commented on js/data/repositroy/twaats.js
> +const addRetwaat = id => firestore.collection(collection)
```suggestion
const retwaat = id => firestore.collection(collection)
```

2019-06-29 17:48 UTC, vodkhard commented on js/data/repositroy/twaats.js
> +const delRetwaat = child =>
```suggestion
const unretwaat = child =>
```

2019-06-29 17:48 UTC, vodkhard commented on js/components/twaat/item.js
> +              >${Object.keys(this.item.laaks).length}</app-button>
```suggestion
              >${this.item.laaks.length}</app-button>
```

2019-06-29 17:48 UTC, vodkhard commented on js/components/twaat/item.js
> +              >${Object.keys(this.item.retwaats).length}</app-button>
```suggestion
              >${this.item.retwaats.length}</app-button>
```

2019-06-29 17:48 UTC, vodkhard commented on js/components/twaat/item.js
> +                .color=${ this.userRetwaat ? '#17bf63' : '' }
```suggestion
                .color=${ this.userRetwaat ? '#17bf63' : null }
```

2019-06-29 17:48 UTC, vodkhard commented on js/components/twaat/item.js
> +                .color=${ this.userRetwaat ? '#17bf63' : '' }
j'ai l'impression ça met pas le bon gris sinon

2019-06-29 17:48 UTC, vodkhard commented on js/components/twaat/item.js
> -
un ptit espace quand même frérot

2019-06-29 17:48 UTC, vodkhard commented on js/data/repositroy/twaats.js
> +const addRetwaat = id => firestore.collection(collection)
Tu devrais dans cette même fonction créer le twaat (pareil que pour les like)

2019-06-29 17:48 UTC, vodkhard commented on js/data/repositroy/twaats.js
> +const delRetwaat = child =>
Tu devrais dans cette même fonction delete le twaat (pareil que pour les like)

2019-06-29 18:02 UTC, LouisHrg commented on js/components/twaat/item.js
> -
Y'a un saut de ligne ça suffit igo

2019-06-29 18:41 UTC, vodkhard commented on js/components/twaat/item.js
> -
Bah ouais mais tu l'as viré le saut de ligne là fraté

2019-06-30 13:43 UTC, LouisHrg commented on js/components/twaat/item.js
> -
Ah ouais déso mon khey

2019-07-01 08:46 UTC, vodkhard commented on js/components/twaat/item.js
> +      try {
narvalo

2019-07-03 08:09 UTC, vodkhard commented
resolve #5

2019-07-16 16:51 UTC, LouisHrg commented on js/data/repositroy/twaats.js
> +const hasUserRetwaat = id => firestore.collection(collection)
rien compris

2019-07-16 17:51 UTC, LouisHrg commented on js/components/twaat/item.js
> +      try {
Ok

2019-07-17 15:11 UTC, vodkhard approved these changes

2019-07-17 15:11 UTC, merged